### ISSUE TITLE
I made a version of this Resource Pack that works with Java Edition. Could you link it so people looking for the Java Edition can download it?

### ISSUE THREAD

**Issue by yashendra2797** [eternalphane/transparent-armor-texture#1]
Hey there!

As the title says, I forked your Repo, and renamed some files, so the pack now works with Java. I've provided complete credit at every step possible. You can view it here: https://github.com/yashendra2797/transparent-armor-texture

I'm requesting that you add these lines to your README.md file at the bottom, so that people who come here to find Transparent Armor Textures for Java can simply be redirected.

Thanks!

```
# Minecraft Java Edition:

This version only works on Minecraft Bedrock Edition.

For those looking for a version of this Resource Pack that works with Java Edition, check out [@yashendra2797](https://github.com/yashendra2797)'s fork [here](https://github.com/yashendra2797/transparent-armor-texture).
```

**Comment by eternalphane** [comment]
In fact I'm planning to remove this repo and upload all my addons to a single repo. Anyway I'll add this to README.md.

**Comment by yashendra2797** [comment]
Thank you!
